# Use postgres/example user/password credentials
version: '3.9'

#docker-compose -f nombre del archivo up -d
#docker start mongodb
#docker-compose -f postgresql.yml up -d

services:

  db:
    image: postgres:17-alpine3.20
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
